spring:
  application:
    name: youthcon-mongodsl
  data:
    mongodb:
      uri: ENC(oVIibBHTW29qKbJ8FSlDVr2Ygx4162vNHZ6rMPcc03aLAe2KpPWaLeQLi4fvyp+WnMUqXrXvxn+TTPpQaxxivFvyJ5qoYaeMXhd+B6UjcJTsWojc3Wgf/Q==)